Create emote-ssh-stable-commands.md
microsoft/vscode-remote-release pull request #7725
Opened 2022-12-16 16:51 UTC by eleanorjboyd

Closes https://github.com/microsoft/vscode-remote-release/issues/7549 We got this request from an extension developer, in addition to just writing this doc we would have to commit to maintaining these functions. I think this is reasonable given how vital they are to the core functionality of the Remote-SSH extension. If this is carried through, comments should be added alongside the functions and the interface to alert future developers.

2022-12-16 16:51 UTC, eleanorjboyd commented
Another note- this could also go in the remote-release wiki. I am not sure which is a better spot for it.

2023-01-04 18:53 UTC, sophacola approved these changes

2023-01-04 18:54 UTC, sophacola approved these changes

2023-02-06 08:34 UTC, Gesisfm commented
diff --git a/emote-ssh-stable-commands.md b/emote-ssh-stable-commands.md
new file mode 100644
index 0000000..f948cba
--- /dev/null
+++ b/emote-ssh-stable-commands.md
@@ -0,0 +1,34 @@
+The Remote-SSH extenions is a private repos that other extensions rely on for varying functionality. Below is a list of commands that we will do our best to keep stable similar to an API. These commands, now published externally here, will be maintained and changes will not be made without sufficent warning to allow for other dependent extensions to function correctly.
+
+
+## Remote-SSH Stable Commands:
+
+#### `opensshremotes.openEmptyWindow`
+- parameters: `(args?: IOpenWindowsArgs)` _(see IOpenWindowsArgs definition below)_
+- this command is called with the command palette command `Connect to Host..`
+
+#### `opensshremotes.openEmptyWindowInCurrentWindow`
+- parameters: `(args?: IOpenWindowsArgs)` _(see IOpenWindowsArgs definition below)_
+- this command is called with the command palette command "Connect Current Window to Host..."
+
+
+#### `opensshremotes.cleanRemoteServer`
+- parameters: none
+- this command is called with the command palette command "Kill VS Code Server on Host..."
+
+#### `opensshremotes.cleanDevBox`
+- parameters: none
+- this command is called with the command palette command "Uninstall VS Code Server from Host..."
+
+## Interface Definitions
+
+##### IOpenWindowsArgs Definition
+```
+interface IOpenWindowsArgs {
+	host: string;
+	userName?: string;
+	port?: number;
+}
+```
+
+

2023-02-16 20:00 UTC, roblourens commented on emote-ssh-stable-commands.md
> +#### `opensshremotes.cleanDevBox`
Actually, do you know whether some other extension depends on these kill commands? We might really need to expose them as API.

2023-02-16 20:00 UTC, roblourens commented on emote-ssh-stable-commands.md
> +- parameters: `(args?: IOpenWindowsArgs)` _(see IOpenWindowsArgs definition below)_
You could link to the args definitions using a link with `#` if you want, or list it first

2023-02-16 23:43 UTC, eleanorjboyd commented on emote-ssh-stable-commands.md
> +The Remote-SSH extension is a private repo that other extensions rely on for varying functionality. Below is a list of commands that we will do our best to keep stable like an API. These commands, no
ok sounds good- ill change the wording to demonstrate a high level of commitment about us maintaining this.

2023-02-17 00:20 UTC, eleanorjboyd commented on remote-ssh-stable-commands.md
> +- this command is called with the command palette command "Uninstall VS Code Server from Host..."
I don't think I full understand how `cleanRemoteServer` and `cleanDevBox` differ. From my understanding, it is just that `cleanDevBox` logs the output of this action, runs showInformationMessage to pop up info and handles the cleaning in a try-catch block which displays an additional message back to the user based on success / failure. I would want to have a clear distinction between the two in this doc so help clarifying would be great.

2023-02-17 00:20 UTC, eleanorjboyd commented on emote-ssh-stable-commands.md
> +#### `opensshremotes.cleanDevBox`
I am not sure- how would I tell?

2023-02-17 00:22 UTC, eleanorjboyd commented on remote-ssh-stable-commands.md
> +
do we want to surface `opensshremotes.openConfigFile`? Not sure if the azure team would benefit from this.

2023-02-17 14:50 UTC, roblourens commented on emote-ssh-stable-commands.md
> +#### `opensshremotes.cleanDevBox`
Oops I meant to say "not really". But I don't think we should add them to this list unless someone asks for it. People can use them through the command palette.

2023-02-17 14:53 UTC, roblourens commented on remote-ssh-stable-commands.md
> +- this command is called with the command palette command "Uninstall VS Code Server from Host..."
The naming isn't great, but `cleanRemoteServer` only deletes the server bits that were installed, while `cleanDevBox` deletes _everything_ including remote extensions and user data

https://github.com/microsoft/vscode-remote-ssh/blob/7d7471b56c345ab22e1bf391126f86722dcacba4/open-ssh-remote/src/commands.ts#L141-L163

2023-02-17 14:54 UTC, roblourens commented on remote-ssh-stable-commands.md
> +
I don't think they would. We don't want them to add temporary az ssh configs to a real config file.

2023-02-17 15:00 UTC, roblourens commented on remote-ssh-stable-commands.md
> +The Remote-SSH extension is a private repo that other extensions rely on for varying functionality. Below is a list of commands that we will comitt to keeping stable like an API. These commands, now
Don't say that we'll make breaking changes but warn extension authors about it. That conflicts with saying that we are committing to keeping it stable. We shouldn't make breaking changes.

2023-02-17 15:00 UTC, roblourens commented on remote-ssh-stable-commands.md
> +### My Multi Word Header
?

2023-02-17 17:09 UTC, eleanorjboyd commented on emote-ssh-stable-commands.md
> +#### `opensshremotes.cleanDevBox`
it was requested by a user here: https://github.com/microsoft/vscode-remote-release/issues/7549 which is why I included it. Do you want me to confirm they use it?

2023-02-17 17:09 UTC, eleanorjboyd commented on remote-ssh-stable-commands.md
> +
sounds good

2023-02-17 17:11 UTC, eleanorjboyd commented on remote-ssh-stable-commands.md
> +`interactivelyPickSshHost` This is an additional function which is called by both `opensshremotes.cleanRemoteServer` and `opensshremotes.cleanDevBox`. This command causes an interactive popup to appe
What do you think is the best way to outline the flow where the host is picked via this picker but not an argument in the two kill commands? Would it work to have it explained separately in this doc but described as not surfaced or should I instead abbreviate its use in the two kill commands just to describe how the specific host to kill is chosen?

2023-02-17 20:22 UTC, roblourens commented on emote-ssh-stable-commands.md
> +#### `opensshremotes.cleanDevBox`
Yeah ask them what they want to use it for

2023-02-17 20:22 UTC, roblourens commented on remote-ssh-stable-commands.md
> +`interactivelyPickSshHost` This is an additional function which is called by both `opensshremotes.cleanRemoteServer` and `opensshremotes.cleanDevBox`. This command causes an interactive popup to appe
That's one reason why that command feels weird as API, because it's only interactive.

2023-02-17 20:51 UTC, eleanorjboyd commented on remote-ssh-stable-commands.md
> +`interactivelyPickSshHost` This is an additional function which is called by both `opensshremotes.cleanRemoteServer` and `opensshremotes.cleanDevBox`. This command causes an interactive popup to appe
ok ill wait to hear back from the other extension developer

2023-03-06 12:24 UTC, fanch1122 commented
**I got this trouble when i install a new vscode,In fact I have two IDcards for one SSH，and I had try  to log the server without password,but i'm failed.
now,the OUTPUT's result is under:**
----------------------------------------------------------------
[20:06:24.706] Got password response
[20:06:24.707] "install" wrote data to terminal: "********"
[20:06:24.720] > 
[20:06:25.585] > d050f2f08e0a: running
[20:06:25.657] > Acquiring lock on /run/user/1027/vscode-remote-lock.fanchenghu.92da9481c0904c6ad
> fe372c12da3b7748d74bdcb
[20:06:25.683] > Found existing installation at /home/user/.vscode-server/bin/92da9481c0904
> c6adfe372c12da3b7748d74bdcb...
> Checking /home/user/.vscode-server/.92da9481c0904c6adfe372c12da3b7748d74bd
> cb.log and /home/user/.vscode-server/.92da9481c0904c6adfe372c12da3b7748d74
> bdcb.pid for a running server
> Looking for server with pid: 215799
[20:06:25.796] > Found running server...
--------------------------------------------------------------------

**what I can do for  this trouble?**

2023-03-06 16:21 UTC, eleanorjboyd commented
@fanch1122 please create an issue for this bug if you would like assistance

2023-03-22 10:02 UTC, lukins requested changes
A je to

2023-03-22 10:03 UTC, lukins approved these changes

2023-03-22 10:04 UTC, lukins reviewed
To bych potřeboval

2023-03-22 15:00 UTC, lukins requested changes
Opraveno

2023-03-22 15:01 UTC, lukins commented
OS Aplet pro SSH stabilitu

2023-04-28 17:59 UTC, eleanorjboyd commented on emote-ssh-stable-commands.md
> +#### `opensshremotes.cleanDevBox`
no response so removing until another request is made for them

2023-05-04 22:25 UTC, roblourens commented on remote-ssh-stable-commands.md
> +The Remote-SSH extension is a private repo that other extensions rely on for varying functionality. Below is a list of commands that we will comitt to keeping stable like an API. These commands, now
There is still a typo for commit

2023-05-04 22:29 UTC, roblourens commented on remote-ssh-stable-commands.md
> +The Remote-SSH extension is a private repo that other extensions rely on for varying functionality. Below is a list of commands that we will comitt to keeping stable like an API. These commands, now
I don't think any of this paragraph of necessary, you can just delete it

2023-05-04 22:29 UTC, roblourens commented on remote-ssh-stable-commands.md
> +##### IOpenWindowsArgs Definition
Why does this go from a level 2 to level 5 markdown header?

2023-05-26 11:53 UTC, Sammiegirl411 approved these changes

2023-05-26 11:54 UTC, Sammiegirl411 approved these changes
As long as I get my payout

2023-05-26 11:55 UTC, Sammiegirl411 approved these changes
Let's run this n see if it works

2023-05-26 11:55 UTC, Sammiegirl411 approved these changes
Let's run this n see if it works

2023-12-23 09:48 UTC, rizwan-r-r approved these changes

2024-02-22 09:26 UTC, Emraja123 approved these changes

2025-01-01 06:49 UTC, Zakariyamuyideen commented on remote-ssh-stable-commands.md
> +The Remote-SSH extension is a private repo that other extensions rely on for varying functionality. Below is a list of commands that we will comitt to keeping stable like an API. These commands, now
Run

2025-01-01 06:49 UTC, Zakariyamuyideen approved these changes

2025-01-05 19:34 UTC, Zakariyamuyideen approved these changes

2025-05-01 09:40 UTC, Jorslope approved these changes

2025-05-01 15:30 UTC, eleanorjboyd commented
@roblourens and @joshspicer forgot this was still open... @joshspicer your decision if you wa nt to go with something like this

2025-12-17 00:25 UTC, closed without merging